apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: studio-payment-scaleobject
  namespace: studio-payment-namespace
spec:
  scaleTargetRef:
    deploymentName: dotnetworld
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 4
  triggers:
  - metadata:
      desiredReplicas: "4"
      start: 40 * * * *
      end: 45 * * * *
      timezone: Asia/Kolkata
    type: cron